repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      #- id: no-commit-to-branch
      #  args : [--branch, main]
      - id: mixed-line-ending
      - id: check-toml
      - id: check-merge-conflict

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [ flake8-typing-imports==1.7.0 ]

  - repo: local
    hooks:
    - id: black
      name: black
      language: system
      entry: black
      minimum_pre_commit_version: 2.9.2
      require_serial: true
      types_or: [python, pyi]

    - id: pytest
      name: pytest
      stages: [commit]
      language: system
      entry: poetry run pytest -s -v .
      types: [python]
      pass_filenames: false
      always_run: true

#  - repo: https://github.com/commitizen-tools/commitizen
#    rev: v2.20.0
#    hooks:
#      - id: commitizen
#        stages: [commit-msg]
