repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args : [--branch, main, --branch, release]
      - id: mixed-line-ending
      - id: check-toml
      - id: check-merge-conflict
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [ flake8-typing-imports==1.7.0 ]
  -   repo: https://github.com/ambv/black
      rev: 21.9b0
      hooks:
      - id: black
        language_version: python3.9
